### ISSUE TITLE
define lifetime

### ISSUE THREAD

**Issue by briner** [skurfer/python-xymon#1]
Hi,

as the "xymon message syntax" is [defined](https://www.xymon.com/help/manpages/man1/xymon.1.html), we can specify a lifetime:
```
status[+LIFETIME][/group:GROUP] HOSTNAME.TESTNAME COLOR <additional text>
```
how can I do to specfiy it in the xymon python module ?

**Comment by briner** [comment]
oups, sorry, I finally get a look at the code, and the lifetime could be defined as the parameter "interval" in Xymon().report.

**Comment by skurfer** [comment]
Yes, if you run

``` python
from xymon import Xymon
help(Xymon)
```

you can see those details, but maybe that’s not the most obvious thing. 😃
